name: child-growth-analyzer
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - streamlit
  - pandas
  - pillow
  - plotly
  - scikit-learn
  - numpy
  - pip:
    - openai